#!/usr/bin/env python
import os
import shutil
import schedule
import time
from time import sleep
from datetime import datetime
from pathlib import Path

def job1():

	timestamp = str(datetime.now())
	path1 = Path("U:\FOR_VALIDATION\VPC2\KPI\LEVEL_1\Ptáček Evžen")
	os.chdir(path1)
	x = sum(os.path.isdir(folder) for folder in os.listdir(path1))
	print(x)

	path2 = Path("C:\Users\anotator\Desktop\VAL\KPI")
	os.chdir(path2)
	y = sum(os.path.isdir(folder) for folder in os.listdir(path2))
	print(y)
	#print("From:"  path1, "To:", path2, timestamp[:19])
	if y < 6 and x > 0:
		os.chdir(path1)
		files = sorted(os.listdir(os.getcwd()), key=os.path.getmtime)
		oldest = files[0]
		newest = files[-1]
		for oldest in files:
			shutil.move(oldest, path2)
			sleep(1)
			append1 = open(r"C:\Users\anotator\Desktop\VAL\data\report\Premistovac-DATA.txt", "a")
			append1.write("From:" + str(path1) + oldest + ' ' " To:" + str(path2) + oldest + ' ' + str(timestamp[:19]) + "\n")
			append1.close()
			sleep(1)

			break
	elif x == 0:
			print('NO MORE TO MOVE')

def job2():
	append2 = open(r"C:\Users\anotator\Desktop\VAL\data\report\Report.txt", "a")
	append2.write(str(timestamp[:19]) + "\n")
	append2.close()
	sleep(1)



schedule.every().day.at("15:00").do(job2)
#schedule.every().hour.do()
schedule.every(10).minute.do()
#schedule.every(15).seconds.do(job1)

while 1:
	schedule.run_pending()
	sleep(1)
